### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by bolshakoff** [jan-zabloudil/release-manager#10]
I am a bit lost. 😄 
Would love to see at least:
- [ ] Introduction, motivation
- [ ] Maybe comparison to other existing solutions
- [ ] Usage
- [ ] Demo (at least screenshots or something) 🤙

**Comment by bolshakoff** [comment]
Most of it can now be found in Notion summary, so closing this one.

**Comment by jan-zabloudil** [comment]
![release-manager 2](https://github.com/jan-zabloudil/release-manager/assets/81581922/3286058f-e3f9-43bb-b0ab-9fc4e050ccea)
