### ISSUE TITLE
Rethink services and repositories structure

### ISSUE THREAD

**Issue by jan-zabloudil** [jan-zabloudil/release-manager#23]
**Context and solution**

The problem I am facing is well described [in this article](https://threedots.tech/post/common-anti-patterns-in-go-web-applications/#starting-with-the-database-schema) under the section `Starting with the database schema.` I  encourage you to read it first (just mentioned section) to provide context for our discussion here.

**Background**

This issue was originally created to consider [suggestion](https://github.com/jan-zabloudil/release-manager/pull/21#discussion_r1581115404) by @bolshakoff to move `environment` to separate service. 

Originally i had it in separate service and then @CermakM suggested to move it under Project service with advice to structure services by domains. I did it but I still kept repositories separated (`Project repository` and `Environment repository`). 

Now I have realized it was mistake and I should (probably) remove `EnvironmentRepository` and have only `ProjectRepository`. And not only that. I think I should also move all logic from `ProjectMembershipService` (invitations and members) to `ProjectService` as well (the same with repository). Why? I try to explain.

**My problem**

Well I had exactly the same problem as one in the article. I want to create project and together with that I also want to create project member. But I have separated repositories and I didn't know where to put repository function responsible for it.

**Solution**

Have only `ProjectService`:

```
* for better readibility I removed functions params

type ProjectService interface {
    CreateProject()
    GetProject()
    ListProjects()
    UpdateProject()
    DeleteProject()
    
    CreateEnvironment()
    GetEnvironment()
    ListEnvironments()
    DeleteEnvironment()
    UpdateEnvironment()
    
    Invite()
    ListInvitations()
    CancelInvitation()
    AcceptInvitation()
    RejectInvitation()
    
    ListMembers()
    RemoveMember()
    UpdateMember()
}
```

And `ProjectRepository`:

```
* for better readibility I removed functions params

type ProjectRepository interface {		
    CreateProject(ctx context.Context, p svcmodel.Project, owner svcmodel.ProjectMember) (svcmodel.Project, error) // creates project and adds project member
    ReadProject()
    ReadAllProjects()
    UpdateProject()
    DeleteProject()
    
    CreateEnvironment()
    ReadEnvironment()
    ReadEnvironemntByName() 
    ReadEnvironmentsForProject()
    DeleteEnvironment()
    UpdateEnvironment()
    
    Invite() 
    ReadInvitation()
    ReadInvitationByEmail()
    ReadInvitationByTokenHashAndStatus()
    ReadInvitationsForProject()
    UpdateInvitation()
    DeleteInvitation()
    
    AcceptInvitation(ctx context.Context, i svcmodel.ProjectInvitation) // only accepts invitation if user is not registered yet
    RejectInvitation(ctx context.Context, i svcmodel.ProjectInvitation)  
    JoinProject(ctx context.Context, m svcmodel.ProjectMember) // registered user joins the project and invitation is removed
    
    ReadMembersForProject()	
    DeleteMember()
    UpdateMember()
}
```

Of course, having all these functions in one `service/project.go` or `repository/project.go` file would be too much. However, you can still organize them into separate files to make it easier to navigate the service/repository, such as `service/project`, `service/project_invitation`, `service/project_environment`, and so on. Or [separate package.](https://github.com/jan-zabloudil/release-manager/issues/23#issuecomment-2081458267)

And by having only one service, any possible circular dependencies would be avoided. Of course, there are boundaries. `Release` should definitely have its own service and repository.

What do you think?

**Comment by jan-zabloudil** [comment]
@bolshakoff This proposal addresses the concern you raised [here](https://github.com/jan-zabloudil/release-manager/pull/21#discussion_r1581115404). All function names now include the object name (e.g., CreateX -> CreateProject, CreateEnvironment, etc.), making it easier to navigate the code

**Comment by jan-zabloudil** [comment]
Or it might be better to create a separate package for each service or repository. 
As a downside of this, you have more imports to manage.

How would this look in the case of a project service:

```
└── service/
    ├── auth
    ├── project/
    │   ├── interface/
    │   │   └── interface.go
    │   ├── model/
    │   │   ├── environment.go
    │   │   ├── environment_test.go
    │   │   ├── invitation.go
    │   │   ├── invitation_test.go
    │   │   ├── member.go
    │   │   ├── member_test.go
    │   │   ├── project.go
    │   │   └── project_test.go
    │   ├── environment.go
    │   ├── environment_test.go
    │   ├── invitation.go
    │   ├── invitation_test.go
    │   ├── member.go
    │   ├── member_test.go
    │   ├── project.go
    │   └── project_test.go
    ├── settings
    ├── user
    └── service.go
```

**Comment by CermakM** [comment]
@jan-zabloudil I believe what you've arrived at is something that we often stumble upon as well, especially at the beginnings when we initially tested DDD pattern, we often split the domains more than necessary and later on realized that it's actually beneficial to have them more compact and excessive separation of services is more of an overhead and sometimes even an obstacle.

TDLR; I don't think it's bad to have a bigger domain / service / repository and what you have here is actually still a rather small service, so don't worry about that! I think the solution makes sense 👍

**Comment by bolshakoff** [comment]
Aha, now I see where did you take the `Request` / `Response` suffixes. 😄 
Nice article, btw.

Before commenting, I would just add that there is at least one more approach (that I had quite a success with):
- Keep the services dumb, i.e. basically CRUD wrappers around the corresponding repositories.
- Once there is a need to have a cross-service call, for example `Invite()`, have a higher-level service, called for example `ProjectManagementService` that would work on top of the "dumb" `ProjectService` and `MembershipService`.

But your approach with "flattening" everything into one service looks fair as well.
Maybe even more idiomatic when it comes to DDD.
(Especially given that we will have another, `Release` domain, so it won't be too boring with only one `Project` service. 😄)

Anyway, love that you went deep into that! 💪

**Comment by bolshakoff** [comment]
A bit more detailed comment.

>@bolshakoff This proposal also addresses the concern you raised https://github.com/jan-zabloudil/release-manager/pull/21#discussion_r1581115404. All function names now include the object name (e.g., CreateX -> CreateProject, CreateEnvironment, etc.), making it easier to navigate the code.

💯 👍 

>Invite() 
AcceptInvitation(ctx context.Context, i svcmodel.ProjectInvitation) // only accepts invitation if user is not registered yet
RejectInvitation(ctx context.Context, i svcmodel.ProjectInvitation)  
JoinProject(ctx context.Context, m svcmodel.ProjectMember) // registered user joins the project and invitation is removed

Sounds too high-level for a repository call.
On the repository level, I'd rather expect something like `CreateInvitation()`, `UpdateInvitationStatus()`, `CreateProjectMembership()`, etc.
But yeah, that's exactly the leaky abstraction section you are referring to, where joining a project doesn't have to involve creating a project membership (in general).
So, the repository will be a bit more high-level.
OK, fair.
Really curious how it goes. 🔥

**Comment by bolshakoff** [comment]
Regarding the structure, I'd definitely not split the `Project` service methods into different files.
Since we agree that it is a one separate domain, I'd expect simply one `project.go` or `service.go` file. 🤙 

As for models, having each model in a separate file in `model` folder feels smooth. ✨

**Comment by jan-zabloudil** [comment]
Thank you both for your comments!


> Regarding the structure, I'd definitely not split the `Project` service methods into different files. Since we agree that it is a one separate domain, I'd expect simply one `project.go` or `service.go` file. 🤙
> 
> As for models, having each model in a separate file in `model` folder feels smooth. ✨

Ok, I am on it 💪
