### ISSUE TITLE
Consider error handling improvements

### ISSUE THREAD

**Issue by jan-zabloudil** [jan-zabloudil/release-manager#25]
https://github.com/jan-zabloudil/release-manager/pull/21#discussion_r1581128376

https://github.com/jan-zabloudil/release-manager/pull/29#discussion_r1583100401

https://github.com/jan-zabloudil/release-manager/pull/29#discussion_r1583122465

https://github.com/jan-zabloudil/release-manager/pull/29#discussion_r1583129829

**Comment by bolshakoff** [comment]
I guess you'd arrive at it naturally when debugging the application, but it's good that we make it explicit and maybe even proactive here. 🤙

**Comment by bolshakoff** [comment]
Also, I mentioned a couple times that having errors defined outside the domains / 3rd party services packages doesn't always feel smooth.

I guess can be discussed here.

**Comment by jan-zabloudil** [comment]
Done 🎉
