### ISSUE TITLE
Direct connection to Postgres database

### ISSUE THREAD

**Issue by jan-zabloudil** [jan-zabloudil/release-manager#48]
I should have made this decision a long time ago. However, I have decided to abandon the solution of accessing the database via the Supabase client (PostgREST), as it has given me such a big headache many times :D. I spent many hours on it, learned a lot, and it will be an interesting chapter in my thesis. 

I am still going to use the Supabase client for authentication, of course. However, I will gradually switch the repository implementation and access the database directly. It would also be good for me to practice this approach

I am still going to merge the current PRs, and then I will make these changes in small PRs.

**Comment by bolshakoff** [comment]
Yeah, I think I heard at least one negative review about Supabase client, and zero positive reviews.
So, makes sense. :)

**Comment by jan-zabloudil** [comment]
Done 🎉
